name: Run CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry>=1.1.13
        poetry config virtualenvs.path .venv
        poetry install

    - name: Activate venv
      run: |        
         if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
              source /home/runner/work/lava/lava/.venv/bin/activate
         elif [ "$RUNNER_OS" == "Windows" ]; then
              pwd
              \home\runner\work\lava\lava\.venv\Scripts\activate.ps1
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi

    - name: Run flakeheaven (flake8)
      run: |
        flakeheaven lint src/lava tests/

  security-lint:
    name: Security Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry>=1.1.13
        poetry config virtualenvs.path .venv
        poetry install
    
    - name: Activate venv
      run: |        
         if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
              source .venv/bin/activate
         elif [ "$RUNNER_OS" == "Windows" ]; then
              .venv\Scripts\activate.ps1
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi

    - name: Run bandit    
      uses: tj-actions/bandit@v5.1
      with:
        targets: |
          src/lava/.      
        options: "-r  --format custom --msg-template '{abspath}:{line}: {test_id}[bandit]: {severity}: {msg}'"

  unit-tests:
    name: Unit Test Code + Coverage
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry>=1.1.13
        poetry config virtualenvs.path .venv
        poetry install

    - name: Activate venv
      run: |        
         if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
              source .venv/bin/activate
         elif [ "$RUNNER_OS" == "Windows" ]; then
              .venv\Scripts\activate.ps1
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi

    - name: Run unit tests
      run: |
        pytest
