name: Run CI
on: [push, pull_request]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'poetry'

    - name: Install Lava
      run: poetry install --no-interaction

    - name: Run flakeheaven (flake8)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: flakeheaven lint src/lava tests/

    - name: Run flakeheaven (flake8)
      if: runner.os == 'Windows'
      run: flakeheaven lint src/lava tests/

  security-lint:
    name: Security Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'poetry'

    - name: Install Lava
      run: poetry install --no-interaction

    - name: Run bandit    
      uses: tj-actions/bandit@v5.1
      with:
        targets: |
          src/lava/.      
        options: "-r  --format custom --msg-template '{abspath}:{line}: {test_id}[bandit]: {severity}: {msg}'"

  unit-tests:
    name: Unit Test Code + Coverage
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'poetry'

    - name: Install Lava
      run: poetry install --no-interaction

    - name: Run unit tests
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        git lfs fetch
        git lfs pull
        pytest
        
    - name: Run unit tests
      if: runner.os == 'Windows'
      run: pytest
